version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: article_archiver_api
    volumes:
      - .:/article_archiver_api
    links:
      - redis:redis
      - rabbitmq:rabbitmq
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  redisdata:
  postgres_data:
