version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: article_archiver_api
    volumes:
      - .:/article_archiver_api
    links:
      - redis:redis 
    ports:
      - "8000:8000"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

    volumes:
      - redisdata:/data

volumes:
  redisdata:
