# Generated by Django 3.0.1 on 2020-02-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2086)),
                ('article_hash', models.CharField(max_length=1024)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('byline', models.CharField(blank=True, max_length=256)),
                ('content', models.TextField()),
                ('textcontent', models.TextField()),
                ('length', models.IntegerField()),
                ('word_count', models.IntegerField(null=True)),
                ('top_image', models.CharField(max_length=2086, null=True)),
                ('favicon', models.CharField(max_length=2086, null=True)),
                ('estimated_reading_time', models.IntegerField(null=True)),
                ('excerpt', models.CharField(blank=True, max_length=1024)),
                ('site_name', models.CharField(blank=True, max_length=256)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=2086)),
                ('article_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiver.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article_data')},
            },
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('tos_accepted', models.BooleanField(default=False)),
                ('tos_accept_date', models.DateTimeField(null=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('account_tier', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.ArticleList')),
            ],
            options={
                'unique_together': {('user_article_id', 'tag')},
            },
        ),
    ]
