# Generated by Django 3.0.1 on 2020-01-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='lenght',
            new_name='length',
        ),
    ]
