# Generated by Django 3.0.1 on 2020-01-19 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archiver', '0002_auto_20200119_1822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelist',
            unique_together={('user', 'article_id')},
        ),
    ]
