# Generated by Django 3.0.1 on 2020-01-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0003_auto_20200119_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiver.ArticleList')),
            ],
            options={
                'unique_together': {('user_article_id', 'tag_name')},
            },
        ),
    ]
