# Generated by Django 3.0.1 on 2020-01-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0004_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('user_article_id', 'tag')},
        ),
    ]
