# Generated by Django 3.0.1 on 2020-02-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0005_auto_20200127_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlelist',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articlelist',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
