# Generated by Django 3.0.1 on 2020-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0006_auto_20200201_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
