# Generated by Django 3.0.1 on 2020-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0007_article_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='estimated_reading_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='favicon',
            field=models.CharField(max_length=2086, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='top_image',
            field=models.CharField(max_length=2086, null=True),
        ),
    ]
