# Generated by Django 3.0.1 on 2020-02-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0010_articlelist_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='user_article_id',
            new_name='user_article',
        ),
    ]
