# Generated by Django 3.0.1 on 2020-02-13 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archiver', '0011_auto_20200212_1955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('user_article_id', 'tag')},
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('tos_accepted', models.BooleanField(default=False)),
                ('tos_accept_date', models.DateTimeField(null=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('account_tier', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
